---
- name: Stop ha services
  become: true
  community.docker.docker_compose:
    project_src: "{{ folder }}"
    state: absent

- name: Start ha services
  become: true
  community.docker.docker_compose:
    project_src: "{{ folder }}"
    state: present